#!/bin/bash

pipe_path="/tmp/cushy_pipe"

mkfifo $pipe_path
TEXT=$(curl "$@")
echo "$TEXT" | less

read -p "Are you sure you want to install this software? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "$TEXT" | sh
fi

rm $pipe_path
